REM @ECHO OFF

setlocal

cd %2

git describe --abbrev=0 --tags >%1
set /p TAG=<%1

git show -s "--format=%%h" HEAD >%1
set /p CID=<%1

git diff --shortstat >%1
set /p DRTY=<%1

echo /* This file is automatically generated by commitid.bat */>%1
echo /* Do not edit! */ >>%1
echo. >>%1

echo #define COMMIT_TAG    "%TAG%" >>%1
echo #define COMMIT_ID     "%CID%" >>%1
echo #define COMMIT_DIRTY  "%DRTY%" >>%1

